version: '3.8'

services:
  # Frontend Angular
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cats-app-frontend
    restart: unless-stopped
    environment:
      NG_APP_API_URL: http://localhost:3000
    ports:
      - "80:80"
    networks:
      - cats-app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Red personalizada para comunicación entre servicios
networks:
  cats-app-network:
    driver: bridge
    name: cats-app-network
    external: true
